Fix panic in `FpsOverlay` with disabled `FrameTimeGraph` (#20461)
# Objective

I am getting the following panic on start:

```
thread 'main' panicked at /home/User/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/wgpu-26.0.1/src/backend/wgpu_core.rs:1195:26:
wgpu error: Validation Error

Caused by:
  In Device::create_bind_group, label = 'FrametimeGraphMaterial'
    Buffer with '' label binding size is zero


note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_render::render_asset::prepare_assets<bevy_ui_render::ui_material_pipeline::PreparedUiMaterial<bevy_dev_tools::frame_time_graph::FrametimeGraphMaterial>>`!
```

when registering the `FpsOverlayPlugin` with the frame time graph
disabled by default:

```rust
app.add_plugins(FpsOverlayPlugin {
    config: FpsOverlayConfig {
        text_config: TextFont {
            font_size: 18.0,
            ..Default::default()
        },
        frame_time_graph_config: FrameTimeGraphConfig {
            enabled: false, // causes panic above
            ..Default::default()
        },
        enabled: false,
        ..Default::default()
    },
})
```


## Solution

I went with the most pragmatic fix I could find, since I am no
render/shader expert but I can imagine there is a better way to fix
this, please let me know. My reasoning being:

It does not panic after `update_frame_time_values` called
`buffer.set_data(frame_times.clone().as_slice())`. So I ended up logging
the buffer inside the system, and the first time it is called with empty
`frame_times` it writes it into the `ShaderStorageBuffer` as `[0, 0, 0,
0]`. Doing the same when initializing the storage buffer fixes the panic
on start.

---------

Co-authored-by: James Liu <contact@jamessliu.com>