Remove redundant doc_auto_config (#12682)
# Objective
CI on main has been failing for the following reason:
```
error[E0636]: the feature `doc_auto_cfg` has already been declared
  --> src/lib.rs:48:29
   |
48 | #![cfg_attr(docsrs, feature(doc_auto_cfg))]
   |                             ^^^^^^^^^^^^
```

## Solution
Remove the redundant attribute.