Update `clap` to 3.2 in tools using `value_parser`
**Why?**
The `value_parser` `clap` attribute was added in
[version 3.2.0][0]. With the current version of `3.1.12` users can get
errors like:

```
error: unexpected attribute: value_parser
  --> tools/spancmp/src/main.rs:18:25
   |
18 |     #[clap(short, long, value_parser, default_value_t = 0.0)]
   |                         ^^^^^^^^^^^^
```

[0]: https://github.com/clap-rs/clap/blob/master/CHANGELOG.md#320---2022-06-13