EmptyPathStream is not used on Android (#25551)
# Objective

- Building on Android has a warning:

```
error: struct `EmptyPathStream` is never constructed
   --> crates/bevy_asset/src/io/mod.rs:790:8
    |
790 | struct EmptyPathStream;
    |        ^^^^^^^^^^^^^^^
    |
    = note: `-D dead-code` implied by `-D warnings`
    = help: to override `-D warnings` add `#[expect(dead_code)]` or `#[allow(dead_code)]`
```

## Solution

- Do not build it on Android, it was unused since
https://github.com/bevyengine/bevy/pull/11495