Make `DeprecatedInteraction` public. (#26033)
# Objective

- Fixes #26029 

## Solution

- Made `DeprecatedInteraction` public.
- Removed `#[expect(private_interfaces, ...)]` from Interaction as
`DeprecatedInteraction` is now public.

## Testing
<details>
  <summary>reproduction code</summary>

```rust
use bevy::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(Startup, issue_26029)
        .run();
}

fn issue_26029(query: Query<&Interaction>) {
    println!("{:?}", query);
}
```

</details>

<details>
  <summary>before</summary>

```
error: type `ui::focus::DeprecatedInteraction` is private
 --> issue_26029\src\main.rs:6:5
  |
6 | /     App::new()
7 | |         .add_plugins(DefaultPlugins)
8 | |         .add_systems(Startup, issue_26029)
  | |__________________________________________^ private type

error: type `ui::focus::DeprecatedInteraction` is private
  --> issue_26029\src\main.rs:12:23
   |
12 | fn issue_26029(query: Query<&Interaction>) {
   |                       ^^^^^^^^^^^^^^^^^^^ private type
```

</details>

<details>
  <summary>after</summary>

```
Finished `dev` profile [unoptimized + debuginfo] target(s) in 1m 38s
```

</details>

## AI disclosure

- All work on this PR was done manually by human.