Work around ambiguous `From` error in nightly (#20618)
There's a new `From` built-in macro in nightly, which makes one glob
import ambiguous:

```
Compiling bevy_ecs v0.17.0-dev (/Users/runner/work/bevy/bevy/crates/bevy_ecs)
error[E0659]: `From` is ambiguous
    --> crates/bevy_ecs/src/entity/clone_entities.rs:1391:14
     |
1391 |     #[derive(From)]
     |              ^^^^ ambiguous name
     |
     = note: ambiguous because of a conflict between a name from a glob import and an outer scope during import or macro resolution
note: `From` could refer to the derive macro imported here
    --> crates/bevy_ecs/src/entity/clone_entities.rs:1379:9
     |
1379 |     use super::*;
     |         ^^^^^^^^
     = help: consider adding an explicit import of `From` to disambiguate
     = help: or use `self::From` to refer to this derive macro unambiguously
note: `From` could also refer to the derive macro defined here
    --> /Users/runner/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/prelude/mod.rs:59:13
     |
  59 |     pub use super::v1::*;
     |             ^^^^^^^^^
```

I don't know if this is a Rust bug or a Bevy bug. I'm going for a Bevy
workaround as it's simple and will unblock CI.

`rustc 1.91.0-nightly (2e2642e64 2025-08-16)`
`From` built-in macro tracking issue:
https://github.com/rust-lang/rust/issues/144889
Regression report: https://github.com/rust-lang/rust/issues/145524

## Testing

```
cargo +nightly check -p bevy_ecs
```