Don't leave root during `bench-check`. (#24248)
## Error

During `$ cargo run -p ci -- compile`
 
```text
$ cargo check --benches --target-dir ../target --manifest-path ./benches/Cargo.toml
error: failed to create directory `D:\bevy\..`

Caused by:
  Access is denied. (os error 5)

thread 'main' (16628) panicked at tools\ci\src\ci.rs:62:13:
One or more CI commands failed:
bench-check: Failed to check the benches.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Solution

- Instead of accessing ../target access ./target

## Testing

- Now the command works on my device.