Fix export-content -check
 thread 'main' panicked at tools/export-content/src/main.rs:35:25:
called `Result::unwrap()` on an `Err` value:   × failed to parse metadata in migration guide file set_index_buffer.md
   ╭─[/home/runner/work/bevy/bevy/release-content/migration-guides/set_index_buffer.md:1:8]
 1 │ title: `TrackedRenderPass::set_index_buffer` no longer takes buffer offset
   ·        ▲
   ·        ╰── found character that cannot start any token at line 1 column 8, while scanning for the next token
 2 │ pull_requests: [20468]
   ╰────