Improve suggestion when old name for `Justify` is used (#21056)
# Objective

Rust currently suggests that users try `JustifySelf` when `JustifyText`
(which has been renamed to `Justify`) is used.

## Solution

Add an alias for the old name

## Before

```
warning: `bevy-alt-ui-navigation-lite` (lib) generated 2 warnings
error[E0433]: failed to resolve: use of undeclared type `JustifyText`
   --> examples/infinite_upgrades.rs:526:46
    |
526 |                 TextLayout::new_with_justify(JustifyText::Center),
    |                                              ^^^^^^^^^^^
    |                                              |
    |                                              use of undeclared type `JustifyText`
    |                                              help: an enum with a similar name exists: `JustifySelf`
```

## After

```
warning: `bevy-alt-ui-navigation-lite` (lib) generated 2 warnings
error[E0433]: failed to resolve: use of undeclared type `JustifyText`
   --> examples/infinite_upgrades.rs:526:46
    |
526 |                 TextLayout::new_with_justify(JustifyText::Center),
    |                                              ^^^^^^^^^^^ use of undeclared type `JustifyText`
    |
help: `Justify` has a name defined in the doc alias attribute as `JustifyText`
    |
526 -                 TextLayout::new_with_justify(JustifyText::Center),
526 +                 TextLayout::new_with_justify(Justify::Center),
```

## Testing

Testing with local bevy dependency in a library I am migrating

## Alternatives

Add deprecated type alias