Fix `On::target` not being implemented for an `EntityEvent` without propagation (#21049)
Before #20731, `On::target` was implemented for any `EntityEvent`. After
that PR, it's only implemented for events with
`#[entity_event(propagate)]`.

```rust
entity.observe(|scene_ready: On<SceneInstanceReady>| {
    // Error: "the method `target` exists but its trait bounds were not satisfied".
    info!("Scene entity {} is ready", scene_ready.target()); 
})
```

I suspect the change wasn't intentional. This PR restores the old
behaviour and adds a regression test.

Note that `On::target` is deprecated, but without the fix users will get
an error instead of a deprecation warning.

<details>
<summary>Full error message:</summary>

```
error[E0599]: the method `target` exists for struct `observer::system_param::On<'_, '_, EntityEventA>`, but its trait bounds were not satisfied
    --> crates\bevy_ecs\src\observer\mod.rs:1129:34
     |
285  |     struct EntityEventA(Entity);
     |     ------------------- doesn't satisfy `<_ as Event>::Trigger<'a> = PropagateEntityTrigger<_, EntityEventA, _>`
...
1129 |                 assert_eq!(event.target(), event.event_target());
     |                                  ^^^^^^
     |
    ::: crates\bevy_ecs\src\observer\system_param.rs:38:1
     |
38   | pub struct On<'w, 't, E: Event, B: Bundle = ()> {
     | ----------------------------------------------- method `target` not found for this struct
     |
note: trait bound `<EntityEventA as event::Event>::Trigger<'a> = trigger::PropagateEntityTrigger<_, EntityEventA, _>` was not satisfied
    --> crates\bevy_ecs\src\observer\system_param.rs:153:40
     |
153  |         E: EntityEvent + for<'a> Event<Trigger<'a> = PropagateEntityTrigger<AUTO_PROPAGATE, E, T>>,
     |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ unsatisfied trait bound introduced here
...
156  |     > On<'w, 't, E, B>
     |       ----------------
```

</code>
</details>

## Testing

Hacked `animated_mesh` example to use `On::target`, confirming it worked
and reported the deprecation warning.