Slight changes from the book (#4077)
Not sure if this is the new format, but quickly looking I couldn't wind a easy way to update it in the book

# Objective

* For sample project to compile after first pages of book

got: 

```
  = note: clang: error: invalid linker name in argument '-fuse-ld=/usr/local/bin/zld'
          

error: linking with `cc` failed: exit status: 1
```

## Solution

FIx to correct zld path