enable rendering in bevy_dev_tools for ci testing (#25803)
# Objective

- #24660 broke feature bevy_ci_testing
```
error[E0433]: cannot find module or crate `bevy_render` in this scope
 --> crates/bevy_dev_tools/src/ci_testing/systems.rs:7:5
  |
7 | use bevy_render::view::screenshot::{save_to_disk, Screenshot};
  |     ^^^^^^^^^^^ use of unresolved module or unlinked crate `bevy_render`
  |
help: there is a crate or module with a similar name
  |
7 - use bevy_render::view::screenshot::{save_to_disk, Screenshot};
7 + use bevy_shader::view::screenshot::{save_to_disk, Screenshot};
  |

error[E0433]: cannot find module or crate `bevy_render` in this scope
  --> crates/bevy_dev_tools/src/ci_testing/mod.rs:14:5
   |
14 | use bevy_render::view::screenshot::trigger_screenshots;
   |     ^^^^^^^^^^^ use of unresolved module or unlinked crate `bevy_render`
   |
help: there is a crate or module with a similar name
   |
14 - use bevy_render::view::screenshot::trigger_screenshots;
14 + use bevy_shader::view::screenshot::trigger_screenshots;
   |

error[E0433]: cannot find module or crate `bevy_render` in this scope
  --> crates/bevy_dev_tools/src/ci_testing/systems.rs:30:40
   |
30 |                     move |captured: On<bevy_render::view::screenshot::ScreenshotCaptured>,
   |                                        ^^^^^^^^^^^ use of unresolved module or unlinked crate `bevy_render`
   |
help: there is a crate or module with a similar name
   |
30 -                     move |captured: On<bevy_render::view::screenshot::ScreenshotCaptured>,
30 +                     move |captured: On<bevy_shader::view::screenshot::ScreenshotCaptured>,
   |

For more information about this error, try `rustc --explain E0433`.
error: could not compile `bevy_dev_tools` (lib) due to 3 previous errors
```

## Solution

- enable rendering for bevy_ci_testing

## Testing

- Built it