panic handling cleanup (#25597)
# Objective

- using the panic handler ends up with many extra messages that can be
confusing.
- If we panic in a system we get an output of something like:
```
thread 'Compute Task Pool (23)' (46756) panicked at examples\ecs\error_handling.rs:13:5:
uh oh
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'Compute Task Pool (23)' (46756) panicked at crates\bevy_ecs\src\error\handler.rs:156:1:
Encountered an error in system `error_handling::panicking_system`: System panicked

Encountered a panic in system `error_handling::panicking_system`!

thread 'main' (39812) panicked at crates\bevy_ecs\src\error\handler.rs:156:1:
Encountered an error in system `bevy_app::main_schedule::Main::run_main`: System panicked

error: process didn't exit successfully: `target\debug\examples\error_handling.exe` (exit code: 101)
```
- Fixes https://github.com/bevyengine/bevy/issues/25552

## Solution

- Make panics always call `resume_unwind` in the panic handler. Only
errors are now converted to panics. This required storing the panic
payload inside of BevyError.
- Remove the `eprintln` in `system_completed`. This is redundant with
the information in `BevyError`.
- Remove uses of `PANIC_ORIGINATES_FROM_ERROR_HANDLER`. This is no
longer needed now that panics just unwind.

## Testing

```rust
use bevy::prelude::*;

fn main() {
    let mut app = App::new();
    app.add_plugins(DefaultPlugins);
    app.set_error_handler(bevy::ecs::error::panic);
    app.add_systems(Startup, panicking_system);
    app.run();
}

fn panicking_system() {
    panic!("blah");
}
```
Before
```
thread 'Compute Task Pool (23)' (46756) panicked at examples\ecs\error_handling.rs:13:5:
blah
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'Compute Task Pool (23)' (46756) panicked at crates\bevy_ecs\src\error\handler.rs:156:1:
Encountered an error in system `error_handling::panicking_system`: System panicked

Encountered a panic in system `error_handling::panicking_system`!

thread 'main' (39812) panicked at crates\bevy_ecs\src\error\handler.rs:156:1:
Encountered an error in system `bevy_app::main_schedule::Main::run_main`: System panicked

error: process didn't exit successfully: `target\debug\examples\error_handling.exe` (exit code: 101)
```
After
```
thread 'Compute Task Pool (19)' (52116) panicked at examples\ecs\error_handling.rs:13:5:
blah
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\examples\error_handling.exe` (exit code: 101)
```

We do lose the easy system info, but that info is available in the
backtrace. I could put the eprintln back in if that info is desirable. I
added the eprintln in the past since the backtrace was pretty noisy, but
that was fixed with the bevy backtrace customization.

## Other Considerations

* We should maybe add panic payload message to the output of the other
error handlers.