Fix clippy when `target_os = "windows"` (#21419)
Fixes a clippy error introduced by #21338. Issue was inside a
`#[cfg(target_os = "windows")]` block so it wasn't caught by CI.

```rust
error: this boolean expression can be simplified
   --> crates\bevy_winit\src\state.rs:481:16
    |
481 |             if !self.app_exit.is_some()
    |                ^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `self.app_exit.is_none()`
```

Tested with Rust 1.90.0, Win10, `cargo run -p ci -- lints`, `cargo run
--example window_settings`.