Fix release workflow - enable missing feature (#25952)
# Objective

- Release from CI failed:
https://github.com/bevyengine/bevy/actions/runs/36190816510/job/108255223990
```
   Compiling bevy_image v0.20.0-rc.2
error: Choosing a zstd backend is required for zstd support. Please enable either the "zstd_rust" or the "zstd_c" feature.
  --> /home/runner/.cargo/registry/src/-96a839c764b706b3/bevy_image-0.20.0-rc.2/src/lib.rs:15:1
   |
15 | / compile_error!(
16 | |     "Choosing a zstd backend is required for zstd support. Please enable either the \"zstd_rust\" or the \"zstd_c\" feature."
17 | | );
   | |_^

error: could not compile `bevy_image` (lib) due to 1 previous error
error: failed to verify package tarball
```

## Solution

- enable `bevy_image/zstd_rust`
- also add some env var to speedup the dry run