Allow only parentheses in #[reflect(...)] (#21400)
# Objective

Fixes #8906

#8906 reports that the `reflect` attribute silently fails when using the
`#[reflect[...]]` syntax. I wasn't able to reproduce that issue, so it
was likely resolved in a prior change. This pull request addresses only
the syntax issue.

## Solution

Validate the `Meta::List` delimiter in reflect macro to allow only
`MacroDelimiter::Paren`

## Testing

- Did you test these changes? If so, how?
I run `cargo check --example reflection_types`
- Are there any parts that need more testing?
No
- How can other people (reviewers) test your changes? Is there anything
specific they need to know?
Run `cargo check --example reflection_types`

Then modify the reflection_types example by changing:
```
#[reflect(Hash, PartialEq, Clone)]
pub struct E {
    x: usize,
}
```
to
```
#[reflect[Hash, PartialEq, Clone]]
pub struct E {
    x: usize,
}
```
then run `cargo check --example reflection_types` again it should now
fail with this error:
```
error: `#[reflect = "..."]` must use parenthesis `(` and `)`
```